services:
  mysql:
    container_name: BookStoreAPI-mysql
    image: mysql:9.4.0
    environment:
      MYSQL_ROOT_PASSWORD: yu71
      MYSQL_DATABASE: book_store
      MYSQL_USER: yu71
      MYSQL_PASSWORD: 53cret!
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql-data:
